=== HarkoFMI/XML-university-project/damsCatalogSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="damsCatalog">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="damsList">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="dam" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string" />
                    <xs:element name="region" type="xs:string" />
                    <xs:element name="regionId" type="xs:integer" />
                    <xs:element name="altitude" type="xs:string" />
                    <xs:element name="constructionYear" type="xs:string" />
                    <xs:element name="damWall">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="type" type="xs:string" maxOccurs="1" />
                          <xs:element name="height" type="xs:string" minOccurs="0" />
                          <xs:element name="length" type="xs:string" minOccurs="0" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="lake">
                      <xs:complexType>
                        <xs:sequence>
                            <xs:element name="area" type="xs:decimal" minOccurs="0"/>
                            <xs:element name="full-area" type="xs:string" minOccurs="0"/>
                            <xs:element name="waterVolume" type="xs:string" minOccurs="0" />
                            <xs:element name="waterSupplyPoolArea" type="xs:string" minOccurs="0" />
                            <xs:element name="length" type="xs:string" minOccurs="0"/>
                            <xs:element name="width" type="xs:string" minOccurs="0" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="picture">
                      <xs:complexType>
                        <xs:attribute name="location" type="xs:string" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:integer" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="regions" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="regionInfo" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="regionRef" type="xs:string" use="required" />
                  <xs:attribute name="regionRefId" type="xs:integer" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== HarkoFMI/XML-university-project/damsCatalog.xml
<?xml version="1.0"?>
<!DOCTYPE damsCatalog [
    <!ENTITY pic1 SYSTEM "./damImages/pic1.jpg" NDATA jpg>
    <!ENTITY pic2 SYSTEM "./damImages/pic2.jpg" NDATA jpg>
    <!ENTITY pic3 SYSTEM "./damImages/pic3.jpg" NDATA jpg>
    <!ENTITY pic4 SYSTEM "./damImages/pic4.jpg" NDATA jpg>
    <!ENTITY pic5 SYSTEM "./damImages/pic5.jpg" NDATA jpg>
    <!ENTITY pic6 SYSTEM "./damImages/pic6.jpg" NDATA jpg>
    <!ENTITY pic7 SYSTEM "./damImages/pic7.jpg" NDATA jpg>
    <!ENTITY pic8 SYSTEM "./damImages/pic8.jpg" NDATA jpg>
    <!ENTITY pic9 SYSTEM "./damImages/pic9.jpg" NDATA jpg>
    <!NOTATION jpg PUBLIC "jpg">
]>
<?xml-stylesheet type="text/xsl" href="damsXSLT.xsl"?>
<damsCatalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="damsCatalogSchema.xsd">
  <damsList>
    <dam id="1">
      <name>Язовир Батак</name>
      <region>област Пазарджик</region>
      <regionId>1</regionId>
      <altitude>1107,8 m</altitude>
      <constructionYear>1959 г.</constructionYear>
      <damWall>
        <type>Земнонасипна с глинен зъб</type>
        <height>35 m</height>
        <length>273 m</length>
      </damWall>
      <lake>
        <area>21.4</area>
        <full-area>21,4 km²</full-area>
        <waterVolume>310 000 000 m³</waterVolume>
        <waterSupplyPoolArea>463,29 km²</waterSupplyPoolArea>
      </lake>
      <picture location="pic1"/>
    </dam>
    <dam id="2">
      <name>Язовир Въча</name>
      <region>област Смолян</region>
      <regionId>2</regionId>
      <altitude>540 m</altitude>
      <constructionYear>1975г.</constructionYear>
      <damWall>
        <type>бетонно-гравитачна</type>
        <height>144,5 m</height>
        <length>420 m</length>
      </damWall>
      <lake>
        <area>5</area>
        <full-area>5 km²</full-area>
        <waterVolume>226 200 000 m³</waterVolume>
        <length>15 km</length>
        <width>1,6 km</width>
      </lake>
      <picture location="pic2"/>
    </dam>
    <dam id="3">
      <name>Язовир Искър</name>
      <region>област София</region>
      <regionId>3</regionId>
      <altitude>817.65 m</altitude>
      <constructionYear>1950 – 1954г.</constructionYear>
      <damWall>
        <type>бетонно-гравитачна</type>
        <height>76 m</height>
        <length>204 m</length>
      </damWall>
      <lake>
        <area>30</area>
        <full-area>30 km²</full-area>
        <waterVolume>673 000 000 m³</waterVolume>
        <waterSupplyPoolArea>1046 km²</waterSupplyPoolArea>
        <length>10,9 km</length>
        <width>3,38 km</width>
      </lake>
      <picture location="pic3"/>
    </dam>
    <dam id="4">
      <name>Язовир Доспат</name>
      <region>област Смолян</region>
      <regionId>2</regionId>
      <altitude>1200,5 m</altitude>
      <constructionYear>1968 г.</constructionYear>
      <damWall>
        <type>каменонасипна с глинено ядро</type>
        <height>60,5 m</height>
        <length>230 m</length>
      </damWall>
      <lake>
        <area>22.1</area>
        <full-area>22,1 km²</full-area>
        <waterVolume>449 300 000 m³</waterVolume>
        <waterSupplyPoolArea>495 km²</waterSupplyPoolArea>
        <length>19 km</length>
        <width>3 km</width>
      </lake>
      <picture location="pic4" />
    </dam>
    <dam id="5">
      <name>Язовир Копринка</name>
      <region>област Стара Загора</region>
      <regionId>4</regionId>
      <altitude>390 m</altitude>
      <constructionYear>1955 г.</constructionYear>
      <damWall>
        <type>каменнозидана и земнонасипна дига</type>
        <height>44 m</height>
        <length>488 m</length>
      </damWall>
      <lake>
        <area>8.4</area>
        <full-area>8,4 km²</full-area>
        <waterVolume>140 000 000 m³</waterVolume>
        <length>7,4 km</length>
        <width>1,2 km</width>
      </lake>
      <picture location="pic5"/>
    </dam>
    <dam id="6">
      <name>Язовир Белмекен</name>
      <region>област Пазарджик</region>
      <regionId>1</regionId>
      <altitude>1923 m</altitude>
      <constructionYear>1974 г.</constructionYear>
      <damWall>
        <type>каменнозидана</type>
        <height>88,2 m</height>
      </damWall>
      <lake>
        <area>4.6</area>
        <full-area>4,6 km²</full-area>
        <waterVolume>144 100 000 m³</waterVolume>
        <length>3,98 km</length>
        <width>1,2 km</width>
      </lake>
      <picture location="pic6"/>
    </dam>
    <dam id="7">
      <name>Язовир Бели Искър</name>
      <region>област София</region>
      <regionId>3</regionId>
      <altitude>1900 m</altitude>
      <constructionYear>1939 - 1945г.</constructionYear>
      <damWall>
        <type>бетонна</type>
        <length>500-600 m</length>
      </damWall>
      <lake>
        <area>0.85</area>
        <full-area>0,85 km²</full-area>
        <waterVolume>15 300 000 m³</waterVolume>
        <length>2,8 km</length>
        <width>0,55 km</width>
      </lake>
      <picture location="pic7"/>
    </dam>
    <dam id="8">
      <id>8</id>
      <name>Язовир Ивайловград</name>
      <region>област Хасково</region>
      <regionId>5</regionId>
      <altitude>120 m</altitude>
      <constructionYear>1964г.</constructionYear>
      <damWall>
        <type>бетонно-гравитачна</type>
        <height>71 m</height>
        <length>250 m</length>
      </damWall>
      <lake>
        <area>15.1</area>
        <full-area>15,1 km²</full-area>
        <waterVolume>156 700 000 m³</waterVolume>
        <length>30 km</length>
        <width>1,3 km</width>
      </lake>
      <picture location="pic8"/>
    </dam>
    <dam id="9">
      <name>Язовир Кърджали</name>
      <region>област Кърджали</region>
      <regionId>6</regionId>
      <altitude>331,45 m</altitude>
      <constructionYear>1977г.</constructionYear>
      <damWall>
        <type>бетонно дъгово-гравитачна</type>
        <height>103,5 m</height>
        <length>344 m</length>
      </damWall>
      <lake>
        <area>13.4</area>
        <full-area>13,4 km²</full-area>
        <waterVolume>497 200 000 m³</waterVolume>
        <waterSupplyPoolArea>1882 km²</waterSupplyPoolArea>
        <length>20 km</length>
        <width>1,3 km</width>
      </lake>
      <picture location="pic9"/>
    </dam>
  </damsList>
  <regions>
    <regionInfo regionRef="област Пазарджик" regionRefId="1" />
    <regionInfo regionRef="област Смолян" regionRefId="2" />
    <regionInfo regionRef="област София" regionRefId="3" />
    <regionInfo regionRef="област Стара Загора" regionRefId="4" />
    <regionInfo regionRef="област Хасково" regionRefId="5" />
    <regionInfo regionRef="област Кърджали" regionRefId="6" />
  </regions>
</damsCatalog>
